### ISSUE TITLE
npm install failed

### ISSUE THREAD

**Issue by laurent-claustre** [tiagocoutinho/multivisor#11]
Hi Tiago,
I did use a cond env python 2.7, install conda package nodejs and then run:
npm install
Got the error
npm ERR! code EPROTO
npm ERR! errno EPROTO
npm ERR! request to https://registry.npmjs.org/acorn/-/acorn-4.0.13.tgz failed, reason: write EPROTO 140055286269760:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:252:
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /users/claustre/.npm/_logs/2019-01-31T13_04_00_226Z-debug.log

Any clue ?

Cheers
Laurent

**Comment by tiagocoutinho** [comment]
Hi Laurent, thanks for the report.

Where does npm come from? Did you install it with conda or is it a debian package.

**Comment by laurent-claustre** [comment]
Hi Tiago,
conda package nodejs
nodejs                    10.13.0              he6710b0_0

**Comment by laurent-claustre** [comment]
Hi again, maybe not a good idea to rebuild the webpack bundles. in the meantime I did use the pypi package you provide, it works fine. Now we have to change our ansible recipe to replace supervisor from system to the one installed in the common python env with supervisor.

**Comment by laurent-claustre** [comment]
Hi, no I mean running npm install; npm run build

**Comment by tiagocoutinho** [comment]
Since 5.0.1 I updated all dependencies (it solves some security issues).
It should work now.
If you have time to test it would be great. If not, I can close this one and we reopen it if necessary

**Comment by laurent-claustre** [comment]
Yes, I just tested with 5.0.2, and it works fine. sysadmin did work on removing the proxy setting. So troubles was certainly due to that.
You close it.
Thanks
