### ISSUE TITLE
Vue in development mode is redirecting all requests

### ISSUE THREAD

**Issue by guy881** [tiagocoutinho/multivisor#23]
Hey, I'm running the application for development purpose as suggested in development mode section in readme. I tried to add a new view to the application, but it seems that `proxyTable` configuration is redirecting all requests to `localhost:22000` where production ready version is running, so I am unable to add new view without building the app. If I turn off multivisor on 22000 I get error:

`[HPM] Error occurred while trying to proxy request /d246a8c85e3c24b2c471.hot-update.json from 0.0.0.0:8081 to http://localhost:22000 (ECONNREFUSED)`

I think that all requests to the python application should be somehow prefixed, maybe with `/api`? and that should be in proxy table, so I won't conflict with frontend views. What do you think @tiagocoutinho ?

**Comment by tiagocoutinho** [comment]
Thanks for reporting.
I agree. Would you be willing to make a PR?

**Comment by guy881** [comment]
Great, I will work on that. :)
