### ISSUE TITLE
Web is not aware when multivisor dies

### ISSUE THREAD

**Issue by tiagocoutinho** [tiagocoutinho/multivisor#38]
I had a closer look at #37 and it seems the connection is only checked when the webapp is created on the browser.

I think we can improve this by reacting immediately when the server dies.

I propose to listen to the SSE *onerror* and *onopen* events (see src/multivisor.js:35 - the *streamTo* function)

**Comment by guy881** [comment]
That's great news, I haven't knew about this events. I will try to improve it, you can assign me @tiagocoutinho. :wink:

**Comment by tiagocoutinho** [comment]
Thanks @guy881 you help is appreciated.
