### ISSUE TITLE
Configure and implement basic unit tests

### ISSUE THREAD

**Issue by guy881** [tiagocoutinho/multivisor#41]
Lack of tests is painful. I believe that even basic tests would improve our workflow. Especially it would help with testing on multiple versions of Python.
I am using pytest on a daily basis and I prefer it over unittest for it's simple syntax and less boilerplate code, but that's only my proposition, I am open for others.

I am eager to work on this issue, as it will help me out with testing Python 3 version. :wink:

**Comment by tiagocoutinho** [comment]
Cool! pytest sounds great. I use it quite often.

For the frontend I am ashamed to say I never tried any of the new unit test libraries/frameworks. I don't know what would work best. We can also postpone it to later.

Does milestone 6.0 sound reasonable to you?

**Comment by guy881** [comment]
Fantastic! I would do separate issue for implementing frontend or maybe integration tests? Similar as you, I am not familiar with frontend tests yet.

6.0 sounds good. :)

**Comment by guy881** [comment]
@tiagocoutinho I've made a pull request with some basic tests and configuration. I will be glad if you have a look. For sure there are more tests to write, but if you don't like the concept, then it doesn't have any sense to write next tests using this config ;)

PR: https://github.com/tiagocoutinho/multivisor/pull/44

**Comment by tiagocoutinho** [comment]
I've just merged #44. It is a great starting point. Thanks for taking care of this
