### ISSUE TITLE
Configure continuous integration

### ISSUE THREAD

**Issue by guy881** [tiagocoutinho/multivisor#42]
After configuring tests (issue https://github.com/tiagocoutinho/multivisor/issues/41) it would be great to make them run automatically on supported versions of Python. 
It would be good to also run flake8 and maybe isort?

I find Travis CI easy to configure and it's well integrated with GitHub.

**Comment by tiagocoutinho** [comment]
Sound good.
I actually prefer gitlab CI but since the project is on github I agree it is better to use Travis.
