### ISSUE TITLE
Does it support read childProcess log?

### ISSUE THREAD

**Issue by potoo0** [tiagocoutinho/multivisor#46]
Does it support read childProcess log?

**Comment by guy881** [comment]
As far as I know multivisor doesn't  support such feature. Right now it only supports "tail" log (like `tail -f <filename>`). I don't think supervisor RPC allows for reading log of child processes.

Correct me, if I am wrong @tiagocoutinho.

**Comment by tiagocoutinho** [comment]
# Multivisor web
The multivisor web interface allows you to see a `supervisorctl tail -f <process>` like console:
![multivisor_log](https://user-images.githubusercontent.com/2684070/58455016-8746a000-8120-11e9-802c-b02dc57acf98.png)

To show the previous screen, you need to click the process log menu item:
![multivisor_log3](https://user-images.githubusercontent.com/2684070/58455008-80b82880-8120-11e9-99d5-9b639dd357e6.png)

# Multivisor cli

The multivisor cli does not support this yet. It would be a nice addition.

**Comment by potoo0** [comment]
Great grateful for your answer.
Please allow me to ask another question: Is there have any ways to rewrite url? Such as `https://myhost.com/superMonitor`。I don't expect that webUI always placed under the root of site. Cause I placed my blog under the root of site.

**Comment by guy881** [comment]
You can configure some proxy server like nginx to do that.

**Comment by potoo0** [comment]
Thanks.
