### ISSUE TITLE
Running development version of multivisor server

### ISSUE THREAD

**Issue by guy881** [tiagocoutinho/multivisor#49]
@tiagocoutinho Is it just me, or the way to run multivisor server in README is incorrect?

![image](https://user-images.githubusercontent.com/10159285/58495826-c1dc2700-8178-11e9-8128-d86c5f60d94e.png)

I can run it successfully if I do: `python -m multivisor.server.web -c examples/full_example/multivisor.conf`
I forgot to report it, it's funny that I do this now after a few contributions. :smile:

**Comment by tiagocoutinho** [comment]
Agree. The README is not up to date.

In previous versions of multivisor, before having a CLI, the module was `multivisor.server` but now it should be `multivisor.server.web`

**Comment by guy881** [comment]
Alright, fixed, thank you!
