### ISSUE TITLE
Multivisor support dependencies 

### ISSUE THREAD

**Issue by mdsajid786** [tiagocoutinho/multivisor#52]
Dear All,

I have tried to install multivisour as per the release notes (README.md) file. I have below versions of pip/nodejs/npm/supervisourd. 

![image](https://user-images.githubusercontent.com/30176589/58797589-04d94700-861e-11e9-987c-fc610f630c3e.png)

Could anyone help me, which version of PIP, NodeJs, NPM, SupervisourD has to be installed in my servers?

**Comment by guy881** [comment]
Hello @mdsajid786,
Are you facing any troubles? Everything seems okay except your npm / node which are very old. Personally I have npm 6.5 which comes with node 11.9.

**Comment by mdsajid786** [comment]
Hello @guy881 ,

Yes am facing trouble while installing. while installing pip install . with the previous version, getting below error and asking to upgrade pip version. after upgrade also getting errors. attached logs FYR. 
[console_logs.txt](https://github.com/tiagocoutinho/multivisor/files/3264448/console_logs.txt)

**Comment by mdsajid786** [comment]
Hello Guys, 

can any one help on this ??

**Comment by guy881** [comment]
Hey, thanks for a bump. The warning about old version of pip shows always if you have old version of pip, but it's definitely not the reason of the problem.

The real problem is here:
```bash
building 'regex._regex' extension
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/regex_2
    gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python2.7 -c regex_2/_regex.c -o build/temp.linux-x86_64-2.7/regex_2/_regex.o
    unable to execute gcc: No such file or directory
    error: command 'gcc' failed with exit status 1
```
It seems that you don't have gcc compiler? Are you running some kind of "slim" version of Linux?

**Comment by mdsajid786** [comment]
Thanks for your response. 

I have installed gcc now and got some diff error. attached logs and snapshots. 

I'm not aware on "slim" version of Linux and as i verified its now running on my machine. 

[console_logs2.txt](https://github.com/tiagocoutinho/multivisor/files/3275163/console_logs2.txt)

![image](https://user-images.githubusercontent.com/30176589/59251346-3ddd7100-8c47-11e9-952a-bd15feed96c9.png)
![image](https://user-images.githubusercontent.com/30176589/59251377-4df55080-8c47-11e9-94a1-ed6de853537d.png)

**Comment by guy881** [comment]
Well, you don't have python development files. The procedure for installing those is dependent on your operating system / distribution. To give some reference https://stackoverflow.com/questions/21530577/fatal-error-python-h-no-such-file-or-directory

**Comment by mdsajid786** [comment]
Thanks for your support @guy881 . Now I have successfully installed multivisour on my machine. 

And I tried to start/stop/restart a simple tomcat application through supervisord and multivisour. below one is the config file which is defined. 

(From README.md file i have added all these configs.)
=============================================
[root@instance-1 full_example]# cat  /etc/supervisord.d/apache.conf 
[global]
name=ACME
[rpcinterface:multivisor]
supervisor.rpcinterface_factory = multivisor.rpc:make_rpc_interface
bind=*:9002
[program:apache]
process_name=%(program_name)s
directory=/root/apache-tomcat-7.0.94/bin/
command=sh startup.sh
autorestart=true
autostart=true
startsecs=40
priority=4
startretries=3
stopasgroup=false
user=root
redirect_stderr=true
stderr_logfile=/root/%(program_name)s_stderr.log
stdout_logfile=/root/%(program_name)s_stdout.log
stdout_logfile_maxbytes=5MB
stdout_logfile_backups=10
stopsignal=QUIT
[root@instance-1 full_example]# 
=============================================

Tried to start tomcat through multivisor it's not giving any success response. below is the snapshot. 

![image](https://user-images.githubusercontent.com/30176589/59264164-2068d100-8c60-11e9-94a6-6bb1103fdf30.png)

Then I restarted in backend and verified through multivisor-cli but nothing is showing here in status. below snapshot FYR. 

![image](https://user-images.githubusercontent.com/30176589/59264426-b43a9d00-8c60-11e9-82cc-6f5c1d7d55ac.png)


**Could you please share me one sample file to start multiple applications.**

**Comment by guy881** [comment]
The configuration you posted is for supervisor, multivisor has separate config file. Please read README  once again.

**Comment by mdsajid786** [comment]
Yeah...!!! 

I got it and saw the example files and configured on Tomcat application. below is the configuration but it's not showing in WEB and CLI as well. can you help me to find out the issue? 

![image](https://user-images.githubusercontent.com/30176589/59275534-1a7fe980-8c7a-11e9-9561-e909a3497302.png)

Still its showing old program files only in the multivosour process even after restarting multivisour. 

![image](https://user-images.githubusercontent.com/30176589/59275646-57e47700-8c7a-11e9-824f-564c9b857016.png)

**Comment by guy881** [comment]
Multivisor is still running with config file called `multivisor.conf` which is the one from example I believe, that's why you've got all those processes here.
![image](https://user-images.githubusercontent.com/10159285/59279474-45f7d980-8c64-11e9-9fb0-517a4ac066d6.png)

**Comment by mdsajid786** [comment]
Yes, that example file only I'm using. In those config files, I have added tomcat application config which I shared you the snapshot above. but still, a new process which I have added one is now showing.  

![image](https://user-images.githubusercontent.com/30176589/59317761-f0621200-8ce1-11e9-8665-70c3b96597e0.png)

**Comment by mdsajid786** [comment]
Hello @guy881,

 I got it and issue resolved now. Thanks for your support. 

I have one question here, with this multivisor can we configure mail alerts if any application goes down or shown in exited/stopped state. ?

**Comment by guy881** [comment]
Hey @mdsajid786,
I am glad you got it running. There is no such feature right now, you can open another issue if you're interested in such feature.
