### ISSUE TITLE
Mail Alert configuration Through Multivisor

### ISSUE THREAD

**Issue by mdsajid786** [tiagocoutinho/multivisor#53]
Hi All,

Is it possible to configure email alerts through multivisor if any application is in exited or stop state?

**Comment by tiagocoutinho** [comment]
No, not at the moment.

I would advice doing this using one of the supervisor plugin tools (by means of graphene for example)

You would have to configure each supervisor instance individually. If you have many instances you could use ansible, puppet or salt to automatize this.

**Comment by tiagocoutinho** [comment]
I hope this answered your question.
I am closing the issue. Feel free to reopen if you have more questions :-)
