### ISSUE TITLE
build issue?

### ISSUE THREAD

**Issue by bxlkm** [tiagocoutinho/multivisor#54]
17091 verbose stack     at Promise._fulfill (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:638:18)
17091 verbose stack     at /usr/lib/node_modules/npm/node_modules/bluebird/js/release/nodeback.js:42:21
17091 verbose stack     at <anonymous>
17092 verbose cwd /work/multivisor
17093 verbose Linux 3.10.0-957.10.1.el7.x86_64
17094 verbose argv "/usr/bin/node" "/usr/bin/npm" "install"
17095 verbose node v8.16.0
17096 verbose npm  v6.4.1
17097 error Cannot read property '0' of undefined
17098 verbose exit [ 1, true ]

**Comment by guy881** [comment]
Hello @bxlkm 
Have you tried with more recent node version?
